### ISSUE TITLE
starting dev environment

### ISSUE THREAD

**Issue by dylanjha** [swrobel/meta-surf-forecast#1]
When I run `invoker start` I get this

<details>
  <summary> invoker start</summary>
You can enable OSX notification for processes by installing terminal-notifier gem
.guard : Notice: Your terminal-notifier is older than what terminal-notifier-guard supports, consider upgrading.
[BS] Access URLs:
 -------------------------------------
 UI: http://localhost:3001
 -------------------------------------
 UI External: http://192.168.1.11:3001
 -------------------------------------
[BS] Watching files...
guard : Notice: Your terminal-notifier is older than what terminal-notifier-guard supports, consider upgrading.
00:01:13 - INFO - Bundle already up-to-date
guard : 00:01:13 - INFO - Inspecting Ruby code style of all files
guard : Inspecting 61 files
surf : => Booting Puma
surf : => Rails 5.0.0.1 application starting in development on http://127.0.0.1:9000
surf : => Run `rails server -h` for more startup options
guard : .............................................................
guard : 
guard : 61 files inspected, no offenses detected
guard : 00:01:15 - INFO - Guard is now watching at '/Users/dylanjhaveri/code/meta-surf-forecast'
surf : Puma starting in single mode...
surf : * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
surf : * Min threads: 0, max threads: 16
surf : * Environment: development
surf : * Listening on tcp://127.0.0.1:9000
surf : Use Ctrl-C to stop
</details>

This looks sane to me, I can see the webapp process `surf` is running on 9000

When I visit `http://127.0.0.1:9000` or `http://localhost:9000` I get this error in the invoker output:

<details>
  <summary>Click to expand</summary>
surf : 2016-09-01 00:03:10 -0700: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
surf : 2016-09-01 00:03:10 -0700: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
surf : ---
surf : 2016-09-01 00:03:10 -0700: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
surf : 2016-09-01 00:03:10 -0700: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
surf : ---
surf : 2016-09-01 00:03:10 -0700: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
surf : 2016-09-01 00:03:10 -0700: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
surf : ---
surf : 2016-09-01 00:03:10 -0700: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
surf : 2016-09-01 00:03:10 -0700: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
surf : ---
surf : 2016-09-01 00:03:10 -0700: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
surf : 2016-09-01 00:03:10 -0700: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
surf : ---
surf : 2016-09-01 00:03:10 -0700: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
surf : 2016-09-01 00:03:10 -0700: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
surf : ---
surf : 2016-09-01 00:03:10 -0700: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
surf : 2016-09-01 00:03:10 -0700: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
surf : ---
</details>

Any idea what I'm doing wrong here? I was able to bundle, seed the database and run `rake spitcast:update` and `rake surfline:update`

**Comment by swrobel** [comment]
Visit https://surf.dev

**Comment by dylanjha** [comment]
🤔  still no dice

![privacy_error](https://cloud.githubusercontent.com/assets/764988/18174456/7b581e70-7022-11e6-8961-4e5f481223fe.png)

**Comment by swrobel** [comment]
Click "Advanced" and then "Proceed to surf.dev (unsafe)". Nothing to worry about, you're just connecting to your own machine and it's a self-signed SSL certificate so Chrome freaks out. I have it set up this way because I force SSL for the entire site and want to make sure my local dev environment matches.

**Comment by gaia** [comment]
More recent versions of chrome do not allow overriding ERR_ICANN_NAME_COLLISION. I'd be interested in looking at the site.

**Comment by swrobel** [comment]
@gaia the error is ERR_CERT_AUTHORITY_INVALID and I'm still able to bypass in 59.0.3071.115 macOS. Pull requests are welcome if you have a better solution. I have about 8 tabs open for better local https config but have yet to have time to read them.

**Comment by gaia** [comment]
current stable channel chrome on windows 10 tells me ERR_ICANN_NAME_COLLISION. i have devs bumping into this issue frequently. solution they found is to get public dns, even if dynamic. feel free to close. thanks!!

**Comment by jcohenho** [comment]
"Proceed to surf.dev (unsafe)" is not an option any more. What other suggestions do you have?

**Comment by jcohenho** [comment]
@swrobel it worked perfectly fine when trying the `.test` tld, thanks!  `sudo invoker setup --tld local`, which would set the tld as `.local` did not work however.

**Comment by swrobel** [comment]
oh yeah, that was a typo. corrected that. glad it worked!
