### ISSUE TITLE
Surfline API code

### ISSUE THREAD

**Issue by AbleLincoln** [swrobel/meta-surf-forecast#15]
I've also been working on a project that utilizes the (hidden) Surfline API. Through my research/snooping around I found that Surfline puts all of their source code straight on their website. I guess they are using source maps and forgot to remove them from the production code. Not the best best security on their end, but I ain't mad. Anyway, all of their API calls are right there for the world to see.

It looks like the `api.surfline.com` endpoint is actually a deprecated. Devtools shows me that they're now using `services.surfline.com`, and the config file seems to support this (again, really crappy security having their config file right on their production site).

The good news is we don't have to guess at the API by monitoring their requests, we can just read it straight from the source code. I'll post instructions for how to find the relevant code, as well as some of the code that I've pulled and have found useful so far.

## How to view Surfline source code
1. open Chrome Devtools
1. go to 'Sources' tab
1. code is located under `webpack://` -> `.` -> `src`. Most of the API calls are located in the 'common' folder

I hope this is useful! I think I'll start putting some of this into the meta-surf-forecast code when I get a chance. This is really a cool project!

**Comment by AbleLincoln** [comment]
## Some useful files I pulled off of Surfline.com

### baseFetch.js
The basic HTTP request code that all of their components use. It looks like they are using some kind of access token for security. Because of this I have had some issues running these API calls from a deployed website (I think there are also some CORS issues). Currently I'm only able to request data when I'm running my app from localhost.

You can also see where they insert their base URL: `config.productAPI`. They actually did manage to remove this from the config file (good job Surfline!), but I'm pretty sure this is just `services.surfline.com`. That's what I've been using and it works fine  👍 

You can also see they are using the [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) package for HTTP requests

```js
import fetch from 'isomorphic-fetch';
import cookie from 'react-cookie';
import config from '../config';

const checkStatus = (res) => {
  if (res.status >= 200 && res.status < 300) return res;
  const error = new Error(res.statusText);
  error.response = res;
  error.statusCode = res.status;
  throw error;
};

const parseJSON = response => response.json();

const doFetch = (path, options) => {
  const at = cookie.load('access_token');
  if (at) { // todo remove
    path += `&accesstoken=${at}`; // eslint-disable-line no-param-reassign
  }

  return fetch(`${config.productAPI}${path}`, {
    // headers: {
    //   'X-Auth-AccessToken': cookie.load('access_token'),
    // },
    ...options,
  })
    .then(checkStatus)
    .then(parseJSON);
};

export const createParamString = params => Object.keys(params)
  .filter(key => (params[key] !== undefined && params[key] !== null))
  .map(key => `${encodeURIComponent(key)}=${encodeURIComponent(params[key])}`)
  .join('&');

export default doFetch;
```

### kbyg.js
The code for getting forecasts (wind, wave, weather, etc) and what not for certain spots and regions
```js
import baseFetch, { createParamString } from '../baseFetch';

export const fetchConditionForecast = (spotId, days) =>
  baseFetch(`/kbyg/spots/forecasts/conditions?${createParamString({ spotId, days })}`);

export const fetchWaveForecast = (spotId, days, intervalHours) =>
  baseFetch(`/kbyg/spots/forecasts/wave?${createParamString({ spotId, days, intervalHours })}`);

export const fetchTideForecast = (spotId, days) =>
  baseFetch(`/kbyg/spots/forecasts/tides?${createParamString({ spotId, days })}`);

export const fetchWeatherForecast = (spotId, days, intervalHours) =>
  baseFetch(`/kbyg/spots/forecasts/weather?${createParamString({ spotId, days, intervalHours })}`);

export const fetchWindForecast = (spotId, days, intervalHours) =>
  baseFetch(`/kbyg/spots/forecasts/wind?${createParamString({ spotId, days, intervalHours })}`);

export const fetchRegionalConditionForecast = (subregionId, days) =>
  baseFetch(`/kbyg/regions/forecasts/conditions?${createParamString({ subregionId, days })}`);

export const fetchRegionalWaveForecast = (subregionId, days, intervalHours) =>
  baseFetch(`/kbyg/regions/forecasts/wave?${createParamString({ subregionId, days, intervalHours })}`);
```

### region.js
Gets subregion overview as well as articles for the area

```js
import baseFetch, { createParamString } from '../baseFetch';

export const fetchRegionalOverview = subregionId =>
  baseFetch(`/kbyg/regions/overview?subregionId=${subregionId}`);

export const fetchRegionalArticles = async subregionId =>
  baseFetch(`/feed/regional?${createParamString({ subregionId })}`);
```

### search.js
I think this is pretty neat. This is the endpoint they use for their search bar. This endpoint lets you get the spot ID (plus more info) for a spot just by putting in the same search parameters you would use on Surfline. For instance, just hit `https://services.surfline.com/search/site?q=venice` and you will get a bunch of spot data for Venice Beach. Pretty sweet!

```js
```

**Comment by pmanning11** [comment]
Wow epic job reverse engineering that @AbleLincoln.  I just used the based url with a region ID and added the 'days' parameter to get multiple results.  However, it looks like the max days are only 6 then I get a message 'parameter out of bounds'.  Any idea how to get the extended forecast?

**Comment by B-Roc** [comment]
@AbleLincoln Would you be interested in developing a widget for use on our website? We are looking to have someone develop a surf forecast/conditions widget. Something that displays swell status (ex. flat-clean with swell direction and period), water temp, high tide/low tide, and any other info you can incorporate. Something like this, only better! Thanks. 
<img width="940" alt="screen shot 2018-12-09 at 9 48 31 am" src="https://user-images.githubusercontent.com/25808617/49699708-250dd900-fb9a-11e8-891b-ec71f78a24ba.png">

**Comment by AbleLincoln** [comment]
@B-Roc I would absolutely be interested. I wonder if this is the best place to discuss this, though. Could you invite me to whatever repo you are developing on and we can discuss there?

**Comment by B-Roc** [comment]
> @B-Roc I would absolutely be interested. I wonder if this is the best place to discuss this, though. Could you invite me to whatever repo you are developing on and we can discuss there?

@AbleLincoln Awesome! Could you please supply your contact info through the contact page on our website? https://saltwater-recon.com/contact-page/

**Comment by swrobel** [comment]
Oops, somehow I unwatched my own repo so I wasn't getting notifications! 🤦🏼‍♂️

Appreciate all of the insight and happy to host this discussion (and others like it) here!

**Comment by JaredDahlke** [comment]
new api call: [https://services.surfline.com/kbyg/spots/forecasts/wave?spotId=5842041f4e65fad6a7708842&days=6&intervalHours=1&maxHeights=false](url)

**Comment by fabriziobertoglio1987** [comment]
My api is free and public. I provide all the info from surfline/magicseaweed. You can find all infos from my website https://fabriziobertoglio.xyz/
https://github.com/fabriziobertoglio1987/surf-rails

**Comment by fabriziobertoglio1987** [comment]
https://github.com/mpiannucci/surfpy/issues/6

**Comment by jakecollins1** [comment]
Thanks for your work on this @swrobel and @AbleLincoln

Is there a list of all spotIDs and regionIDs anywhere? Or a surfline command to get nearby IDs from a zip code or Lat/Long coordinates?

**Comment by swrobel** [comment]
@jakecollins1 this is [documented in the README](https://github.com/swrobel/meta-surf-forecast#adding-spots)

**Comment by jakecollins1** [comment]
@swrobel I didn't communicate my question very well, what I was looking for was a surfline api query for that information.  I ended up finding it by looking into the surfliner code, the query I need is 
https://services.surfline.com/kbyg/mapview/spot?lat={lat}&lon={lon}

Thanks for the quick response though!

**Comment by fabriziobertoglio1987** [comment]
I think the key here is having 15 days surf-forecast without breaking DMCA. https://github.com/mpiannucci/surfpy/issues/6#issue-619432382

The only way is fetching the data from weather station and calculate the forecast yourself..

https://docs.stormglass.io/#/weather?id=point-request
Does not provide longer then 5 days data, so I don't know if you can find alternative service or you have to deduct the forecast by monitoring a further BUOY in the ocean

**Comment by fabriziobertoglio1987** [comment]
this api provides 15 days hourly weather forecast for free until n number of api calls

https://www.weatherapi.com/api.aspx

**Comment by fabriziobertoglio1987** [comment]
@jakecollins1 @swrobel @AbleLincoln let me know if you need some help or want to share some ideas

**LOCATIONS API**
I build an API to query all the surfspots worldwide with all the info (but no forecasts)

The api docs https://documenter.getpostman.com/view/6379421/SVfH1CeA#b3991971-aa89-487f-ac9d-01084bf8bc49
The opensource project https://github.com/fabriziobertoglio1987/surf-rails#surf-database

**ABOUT THE SURF FORECAST**
I think the key here is having 15 days surf-forecast without breaking DMCA. https://github.com/mpiannucci/surfpy/issues/6#issue-619432382

I tried to calculate my own forecast in my backend but it's difficult task 
My opensource project https://github.com/fabriziobertoglio1987/surf-rails#forecast-engine 
Related Discussion https://github.com/mpiannucci/surfpy/issues/6
The API I used https://docs.stormglass.io/#/weather?id=point-request
(the above stormglass api does not provide longer then 5 days data, so I don't know if you can find alternative service or you have to deduct the forecast by monitoring a further BUOY in the ocean)

I think calculating surf forecast on your own is really time consuming and requires specific knowledge of the ocean weather forecast calculation

**CONCLUSION** 
I wonder how we could put together all this ideas in a Mobile/Web app which people would actually use... Any ideas?

**Comment by fabriziobertoglio1987** [comment]
@jakecollins1 I don't see the point of using this api 

>Because of this I have had some issues running these API calls from a deployed website (I think there are also some CORS issues). Currently I'm only able to request data when I'm running my app from localhost.

All this work to build an app from a **non** public api, but there are public apis that provide:

- the surf spots https://documenter.getpostman.com/view/6379421/SVfH1CeA#b3991971-aa89-487f-ac9d-01084bf8bc49
- the surf forecast stormglass.io/

so why build on top of surfline that already has several limitations, no clear documentation  and the service will be discontinued?
