### ISSUE TITLE
Surfline API V2

### ISSUE THREAD

**Issue by Duyvest** [swrobel/meta-surf-forecast#18]
Edit...

Removing the wave, weather, tides e.t.c. give all information in one request...

Thanks for the work on this project and documentation of the different surf API's

I'm working on this product here www.duyvest.com and am looking at adding the surfline API for surf data.

With the V2 api, do you know if it possible to get all the data (wave, tide, weather) with one request?  is there a "all" type?   I would like to create an approx surf rating using wave height, period and wind speed and direction.

thanks again

**Comment by swrobel** [comment]
Not that I'm aware of. I'm also very annoyed that I'm going to have to do
multiple requests but who ya gonna complain to?

**Comment by Duyvest** [comment]
Hey Stefan

Figured it out, just don't put any value in and all type are displayed as one in one request.

https://services.surfline.com/kbyg/spots/forecasts/?spotId=590927576a2e4300134fbed8&days=3&intervalHours=12&maxHeights=false

**Comment by pmanning11** [comment]
@Duyvest have you figured out how to get the up to 2 week forecast?  The days parameter only works up to 6 for me

**Comment by swrobel** [comment]
@pmanning11 see [here](https://github.com/swrobel/meta-surf-forecast#requests) for info on how many days you can get with and without a premium access token.

@duyvest that's a great find, although that forecast doesn't include the data on whether swell/wind are optimal, which means I'll still need to make 2 calls.

**Comment by pmanning11** [comment]
@swrobel thanks for the docs.  Is there a way to find a premium access token?  I have a premium account.
