### ISSUE TITLE
Get Legacy ID from Surfline API

### ISSUE THREAD

**Issue by hislopzach** [swrobel/meta-surf-forecast#23]
I have discovered a way to find a spot's legacy id, and I figured this info might be useful to others. 

The Legacy ID can be found by sending  a request for a spot report (i.e. `https://services.surfline.com/kbyg/spots/reports?spotId=5842041f4e65fad6a7708814` [spot id here is for Rincon]).
This returns a JSON response object, in which the legacy spot id can be accessed from `response.associated.advertising.spotId`

**Comment by swrobel** [comment]
Thanks. Already using this in the [SpotFinder](https://github.com/swrobel/meta-surf-forecast/blob/master/app/models/spot_finder.rb#L61)

**Comment by hislopzach** [comment]
Good to know. You might want to remove this line from the spot_id row of the Surfline v1 Paramus table in the Readme. 

> Unfortunately I'm no longer aware of a way to get legacy spot ids

**Comment by swrobel** [comment]
Good catch. Fixed!
