### ISSUE TITLE
Params problem with Surfline V2

### ISSUE THREAD

**Issue by brunofournies** [swrobel/meta-surf-forecast#26]
Hi, Great project and thanks for sharing.
I'm having trouble getting the data for Surfline V2 api. It's seems no matter what day or interval hours are set, always return 3 days of forecast with a 3 hours interval. Here is the API :

https://services.surfline.com/kbyg/spots/forecasts/?spotId=5842041f4e65fad6a7708cc2&days=6&intervalHours=1

If days are more than 6 its return : 
{
    "message": "Parameters out of bounds"
}

but if you use the "conditions" or "report" api, its works, like https://services.surfline.com/kbyg/spots/conditions/?spotId=5842041f4e65fad6a7708cc2&days=6&intervalHours=1

any idea what is happening?

PD: I have a premium account on Surfline but I don't know how to get the Access token, maybe this is a free account issue

**Comment by swrobel** [comment]
It is a free account issue. You need to use an access token in your requests to get access to all params.

**Comment by brunofournies** [comment]
Thanks!, Can youn tell me how can i get the Access Token? can't find it on the web

**Comment by swrobel** [comment]
My code for it is in this file: https://github.com/swrobel/meta-surf-forecast/blob/master/app/models/surfline_v2.rb

**Comment by brunofournies** [comment]
Yes, im following that, im getting 
{
    "error": "unsupported_grant_type",
    "error_description": "Unsupported grant type: undefined"
}
Any ideas?

**Comment by brunofournies** [comment]
Found the issue, was my problem. Was putting the grant_type into the params filed instead of the body.

Problem solved. thanks for the help!

**Comment by PROTO-IDP** [comment]
> grant_type

Boa noite, consegue nos passar como ficou após corrigido?
