### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Goodsmileduck** [swrobel/meta-surf-forecast#3]
Hi. I want to wrap your app in docker, is it possible to get all variables from system variables?
something like here https://github.com/swrobel/meta-surf-forecast/blob/master/config/environments/production.rb#L20

I mean db url, newrelic token and others..

Sorry, I don't have enough exp with ruby =)

**Comment by swrobel** [comment]
Unfortunately there isn't a comprehensive list of all of the env vars in use in the app. You'll just have to search the project for "ENV[".

Hardcoding the Newrelic key was unintentional. I've changed the newrelic.yml to expect a NEW_RELIC_LICENSE_KEY env var.

It's a little known trick with Rails that you can [just set a DATABASE_URL](http://guides.rubyonrails.org/configuring.html#configuring-a-database) and that will override database.yml.

Good luck, and let me know how it goes!
