### ISSUE TITLE
Spot IDs per country

### ISSUE THREAD

**Issue by TheNerdOne9** [swrobel/meta-surf-forecast#30]
Hi, is there a way to display all the spots ids on surfline API per country? I'm trying to get that list to have a custom map with all the spots in my country but i cant find the way. Can you help me out?

**Comment by swrobel** [comment]
I haven't used that API, but this might point you in the right direction: https://github.com/dssd1001/surfnow/blob/e0c10d3b6e8368493d7c036588364cd84b857635/readme.md#taxonomy
