### ISSUE TITLE
Feature Request: Timeframe Selector

### ISSUE THREAD

**Issue by cduflo** [swrobel/meta-surf-forecast#31]
Hey - great job on this, I find it super useful!

I usually check on mobile to see what the best looking rating is in the county, but it's really difficult to see because the chart lines are so small. If there was a way to select timeframe (**1 Day**, 2 Days, 3 Days, 1 Week, etc), it would be easier to limit the number of data points on the graph and find the relevant data quickly.

![Screen Shot 2020-06-08 at 5 29 52 AM](https://user-images.githubusercontent.com/15986207/84030755-67f46c80-a949-11ea-99be-f0c503ff2840.png)

**Comment by swrobel** [comment]
I'm happy to accept a pull request for this, but I'm not personally interested in implementing it. I've found that simply rotating to landscape is good enough to make the chart usable on my phone (iPhone X)
