### ISSUE TITLE
Notes from Setting this up [DRAFT]

### ISSUE THREAD

**Issue by iarobinson** [swrobel/meta-surf-forecast#33]
### DRAFT ISSUE - INCOMPLETE
This is a work in progress. I don't currently have the application running locally so I'd assume that the notes here will be useful for future developer one day...

Here I'm just making notes on the difficulties I had while setting this up

- I had ruby version and bundler issues... so might want to add those to README.md
- surf.localhost didn't work....
- I had to run this = `brew install terminal-notifier`
- Visiting `https://127.0.0.1:3000/` got me this:
```
2020-09-19 17:39:06 -0500 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>
2020-09-19 17:39:06 -0500 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>
```

- `bin/server` specifically works better than conventional `rails s`
- This error came up:
`Invoker has detected setup has not been run. Domain feature will not work without running setup command.`
- 

<img width="1440" alt="Screen Shot 2020-09-20 at 12 25 44 PM" src="https://user-images.githubusercontent.com/7991933/93717598-acd49580-fb2b-11ea-8e02-e311d948a8b8.png">

Got it working. _Maybe_ I skipped the step where I was supposed to run the following command:

`rvmsudo bin/invoker setup --tld localhost`

But I'm pretty sure I did run it previously. Perhaps the order of the setup lines could be adjusted...

**Comment by swrobel** [comment]
bin/server should start surf.localhost. Did you run that?

**Comment by iarobinson** [comment]
## Application Running Locally! 

But it's not working the way I would expect it to. All the results from the dropdown are showing up blank...

<img width="1440" alt="Screen Shot 2020-09-20 at 12 33 09 PM" src="https://user-images.githubusercontent.com/7991933/93717752-b7dbf580-fb2c-11ea-93e8-4235037ed65c.png">

I don't see any error messages to lead me in the proper direction. I'm also unfamiliar with `.slim` html files so I don't know where to go from here...

**Comment by swrobel** [comment]
Check out https://metasurfforecast.com/ if you want to see it fully functioning. It seems like you're missing forecasting services other than MagicSeaweed. It's true that this isn't documented, but charts won't render if you don't have all of the forecasts loaded for a specific spot - there's not much point in giving a "meta" forecast that's just from a single forecasting service.
