### ISSUE TITLE
Python Port and Tweaks

### ISSUE THREAD

**Issue by Legohead259** [swrobel/meta-surf-forecast#35]
Good day,

I am a college student in Florida and was assigned a homework assignment with the same goal as this project - record surf forecasts. I am not familiar with Ruby and I need a few additional features (like getting data for the NOAA buoys) so I was going to write some Python scripts based off this project. It will be open source and also posted here on GitHub (https://github.com/Legohead259/Surfability-Calculator)

How would you like to be attributed? Would the NOAA API integration be useful to you?

Regards,
-Braidan

**Comment by swrobel** [comment]
I don't really care about attribution and I recently added NDBC buoy data but thanks for checking.
