### ISSUE TITLE
Max/Min/Avg Per Source

### ISSUE THREAD

**Issue by gaia** [swrobel/meta-surf-forecast#6]
Hi Stefan

Have or would you released a (365 days or more) dataset or analysis of which one of the sources tend to fall on which end of the range? As in who tends to over/understate surf size more often? Or is there no pattern to this data?

**Comment by swrobel** [comment]
I'd love to do an analysis but haven't had time. Determining over/under-estimate would require a user feedback mechanism. As for now, I'm discarding old forecasts to save database space.

**Comment by gaia** [comment]
i didn't mean how the forecase diverges from real life. only how they diverge from each other.

**Comment by swrobel** [comment]
Anecdotally, I'd say Surfline is most often the outlier, but I'd honestly have to put effort into adding a lot more spots (pull requests welcome!) in order to do a real analysis that's statistically significant.
